### ISSUE TITLE
All the scripts are missing when open the demo.scene

### ISSUE THREAD

**Issue by Wesloc** [ViveSoftware/MediaDecoder#2]
Unity 5.6.

Open a new project in Unity 5.6 
Drag everything under MediaDecoder-master\UnityPackage into the Asset under unity project 
Open the demo scene. Click on any gameobject. All the attached scripts are missing.

**Comment by kyo8568131** [comment]
Hi Wesloc,
This issue is caused by lack of meta files. I've upload the meta files, please try again.
And you can also visit our plugin page on Unity Asset Store at: https://www.assetstore.unity3d.com/en/#!/content/63938
Thanks.
