### ISSUE TITLE
Unity 5.6: video not playing following the quick guide

### ISSUE THREAD

**Issue by Wesloc** [ViveSoftware/MediaDecoder#3]
Trying to play video in a quad by following the quick guide in readme.

The quad is pink and not showing video. Audio is playing fine. The logs in console appear to be OK. No obvious error.

**Comment by kyo8568131** [comment]
Hi Wesloc,
Pink maybe refer to material or texture missing. Please help to check whether the material exist and shader to be YUV2RGBA. 
Thanks.

**Comment by Wesloc** [comment]
SampleScene is working now. Both video and audio are playing successfully. I will close this issue.

In the Demo scene, the issue of missing scripts has been resolved. 

There are errors when I try to play demo scene. However, it might be caused by the image and video that I am using are not stereo. I will play with this scene a bit further later tonight.

Thanks for the good work!!
