### ISSUE TITLE
nativeLoadThumbnail causes unity editor to crash

### ISSUE THREAD

**Issue by Wesloc** [ViveSoftware/MediaDecoder#4]
To reproduce:
1. load SampleScene
2. uncheck MediaDecoder on the Quad from the Inspector
3. add a new script TestThumbnail.cs to the Quad
```
public class TestThumb : MonoBehaviour {

	// Use this for initialization
	void Start () {
        MediaDecoder.loadVideoThumb(gameObject, "C:\\Users\\video\\swim.mp4", 2);
	}
	
	// Update is called once per frame
	void Update () {
		
	}
}
```
4. nativeLoadThumbnail will crash the unity editor.

**Comment by Wesloc** [comment]
Could someone from Vive confirm if this is a real issue or I did something wrong? The steps are quite simple.

Thank you.

**Comment by kyo8568131** [comment]
Hi Wesloc,
Yes, it is native thumbnail loading issue. I've fixed it.
Thanks.
